sirlyun/algorithm

- BOJ_1043/suheon.py
> BOJ_1043: python

- BOJ_17825/sunghyeon.py.py
> [231024] BOJ_17825

- BOJ_17825/jiwon.py
> ♻️refactor : BOJ_17825 블로그 참고

- PGS_42889/seonghyeon_실패버전.py
> ✨error:PGS_42889 python 오답코드

- BOJ_18430/jiwon.py
> [231026] BOJ_18430 - 1문제

- BOJ_18430/myeongjin.py
- PGS_42889/myeongjin.py
> [231026] BOJ 18430

- BOJ_18430/suheon.py
[231026] {BOJ} {18430} - {오답 코드}
> ✨error: BOJ_18430 오답 코드(시간초과)

- BOJ_18430/suheon.py
> ♻️refactor : BOJ_18430 지원햄 코드 참고

- BOJ_18430/seonghyeon.py
이번 문제 너무 어려워서 명진이형 코드를 참고했답니다.
그렇다고 모든 코드를 베낀건 아니고용.
제 방식대로 조금 수정하긴 했습니다.
우하하
> ♻️refactor:BOJ_18430 갓명진 코드 참고

- BOJ_18430/minjae.java
> ✨error: BOJ_18430 오답 코드

- PGS_118666/jiwon.py
> [231027] PGS_118666 - 1문제

- BOJ_4485/jiwon.py
> [231030] BOJ_4485 - 1문제

- BOJ_4485/suheon.py
- PGS_118666/suheon.py
[231030] {PGS} {118666} - {저번주 금요일 문제}
[231030] {BOJ} {4485}
> 231030_samgakjisam

- PGS_86971/suheon.py
> ✨error: PGS_86971 오답 코드

- BOJ_18430/jiwon.py
- BOJ_4485/jiwon.py
- PGS_86971/jiwon.py
> [231031] PGS_86971 - 1문제

- BOJ_18430/jiwon.py
- BOJ_4485/jiwon.py
> BOJ_4485: python 다시커밋

- BOJ_1520/seonghyeon.py
> BOJ_1520:python

- PGS_42883/jiwon.py
> [231102] PGS_42883 - 1문제

- PGS_42883/myeongjin.py
> [231102] PGS 42883

- BOJ_1939/jiwon.py
> [231103] BOJ_1939 - 1문제

- PGS_42898/Geonwoong.py
> 231106 PGS_42898: python

- PGS_42898/jiwon.py
> PGS_42898: python

- PGS_42898/seonghyeon.py
> PGS_42898:python

- BOJ_1135/seonghyeon1.py
> ♻️refactor : BOJ_1135 블로그 참고

- BOJ_1135/suheon.py
> [231107] {BOJ} {1135} - {refactor}

- PGS_92341/seonghyeon.py
> PGS_92341:python

- PGS_92342/suheon.py
> [231129] PGS 92342 - 1문제

- PGS_12924/ChaCha.java
- PGS_12973/ChaCha.java
[숫자의 표현](https://school.programmers.co.kr/learn/courses/30/lessons/12924)
[짝지어 제거하기](https://school.programmers.co.kr/learn/courses/30/lessons/12973)
> [231221] 오늘의 알고리즘

- ChaCha.java
- PGS_76502/ChaCha.java
[괄호 회전하기](https://school.programmers.co.kr/learn/courses/30/lessons/76502)
[n^2 배열 자르기](https://school.programmers.co.kr/learn/courses/30/lessons/87390)
> [240111] 오늘의 알고리즘

- PGS_12949/ChaCha.java
- PGS_131127/ChaCha.java
[할인 행사](https://school.programmers.co.kr/learn/courses/30/lessons/131127)
> [240116] 오늘의 알고리즘

- BOJ_2304/Cha Cha.java
- PGS_154539/ChaCha.java
- PGS_49994/ChaCha.java
- PGS_92341/ChaCha.java
[뒤에 있는 큰 수 찾기](https://school.programmers.co.kr/learn/courses/30/lessons/154539)
[주차 요금 계산](https://school.programmers.co.kr/learn/courses/30/lessons/92341?language=java)
[창고 다각형](https://www.acmicpc.net/problem/2304)
[방문 길이](https://school.programmers.co.kr/learn/courses/30/lessons/49994)
> [240220 - 240222] 오늘의 알고리즘

- BOJ_1138/ChaCha.java
- BOJ_14940/ChaCha.java
- BOJ_2075/ChaCha.java
- PGS_42584/ChaCha.java
[주식가격](https://school.programmers.co.kr/learn/courses/30/lessons/42584)
[N번째 큰 수](https://www.acmicpc.net/problem/2075)
[한 줄로 서기](https://www.acmicpc.net/problem/1138)
[쉬운 최단거리](https://www.acmicpc.net/problem/14940)
> [240222 - 240223] 오늘의 알고리즘

- BOJ_15989/ChaCha.java
- BOJ_20922/ChaCha.java
- PGS_12913/ChaCha.java
[땅따먹기](https://school.programmers.co.kr/learn/courses/30/lessons/12913)
[겹치는 건 싫어](https://www.acmicpc.net/problem/20922)
[1, 2, 3 더하기 4](https://www.acmicpc.net/problem/15989)
> [240225 - 240226] 오늘의 알고리즘

- PGS_12900/ChaCha.java
[2 x n 타일링](https://school.programmers.co.kr/learn/courses/30/lessons/12900)
> [240415] 오늘의 알고리즘

- BOJ_2138/ChaCha.java
- PGS_42884/ChaCha.java
오랜만이야 설아~
[전구와 스위치](https://www.acmicpc.net/problem/2138)
[단속카메라](https://school.programmers.co.kr/learn/courses/30/lessons/42884)
> [240506 - 240512] 오늘의 알고리즘

- BOJ_7682/ChaCha.java
[틱택토](https://www.acmicpc.net/problem/7682)
> [240526] 오늘의 알고리즘
